version: "3.8"
services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./resources/mysql:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - db_app:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
        ports: 
            - "3307:3307"
        networks:
            - default
    www:
        build:
            context: .
            args:
                DEBIAN_FRONTEND: noninteractive
                TIMEZONE: ${TIMEZONE}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_HOST: ${MYSQL_HOST}
                WP_TABLE_PREFIX: ${WP_TABLE_PREFIX}
        ports: 
            - 80:80
        volumes:
            - ./app:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
    db_app:
